### ISSUE TITLE
Failed to get config: yaml

### ISSUE THREAD

**Issue by ShAd0wJ** [jaksi/sshesame#72]
Could just be I maybe doing something wrong with specifying the .yaml file, however the following file path both absolute and relative file path return an error. I have not changed the example  .yaml file in anyway just to make sure it worked or failed. Unfortunately I keep receiving the error :

“Failed to get config: yaml: line 13: did not find expected key”

what’s interesting is the pointer from the error doesn’t point to any lines having to do with the keys responsible for connection. Originally I had thought after looking at the config file that maybe it was talking about the sshesame program itself, so I downloaded a clone from github so I could read it not in binary like the already compiled go version but line 13 in the main.go also has nothing to do with any of the keys either. I even attempted to point to the directory where they were stored with the flag -data_dir and still got the same error. What could this mean?

**Comment by ShAd0wJ** [comment]
So interesting discovery as I continue to mess around with the program, it will accept the .yaml configuration file from the cloned github repository but not a .yaml config file from any other place within the system even if copied directly from the same file that works

**Comment by jaksi** [comment]
I fixed an issue with the default config vs. what the code expects in https://github.com/jaksi/sshesame/pull/73, could you check if this fixed the issue?
I'll look into the misleading error message and loading the config from a different path in the meantime.

**Comment by jaksi** [comment]
The error message suggests that there's a syntax error with the YAML file provided.
Are you sure the file working and not working yaml files are exactly the same?
What OS and go version are you using?

**Comment by ShAd0wJ** [comment]
Just checked up on both you responses, and the .yaml file I used was directly from the repository. I just copied it over to the same dir to make it easier to specify rather than an absolute path. If the .yaml file in the cloned repository is specified to be the -config then it works. As for OS and GO versions I am using kali linux 2020.3 and Go version 1.15.9. I receive an error message if attempting to run the program directly from the clone that there is a GO version 1.16 however when searching with apt it doesn’t appear and going through the Go packages when searching all possible GO installations it doesn’t appear.

**Comment by ShAd0wJ** [comment]
Also, to your previous message, I did retry the program and after both uninstalling both the cloned repository and the program from my GOPATH, and then reinstalling I still get the same error. But it still works if specifying the file from the clone when using the program from GOPATH.

**Comment by jaksi** [comment]
Apologies for the late response, had a busy couple of weeks.
Just to make sure: do you have the `sshesame` package (https://pkg.kali.org/pkg/sshesame) installed? `sshesame` packages in the standard Debian (& derivatives like Kali) are pretty outdated. Since I'm not sure who packaged it I don't have much control over it. Please make sure you don't have the package installed and build from source or use the docker image (https://github.com/jaksi/sshesame/pkgs/container/sshesame) instead.
